version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
        environment:
          TEST_ENV: "CIRCLECI"
          DATABASE_URL: postgresql://postgres@localhost/circle_test
          CODECOV_TOKEN: $CODECOV_TOKEN
      - image: circleci/postgres:12-alpine-ram
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest --cov=./
      - run:
          name: Upload coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: test-reports/
          destination: foss-library-v2
